name: TylerFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the TylerFreedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials]
authors: [Madgeek1450, Prozza, tylerhyperHD]

# plugin.yml is no longer used to define commands.
